import {Type} from "protobufjs";
import {normalizeComment, writeToFile} from "../utils";
import {snakeCase} from "change-case"

export async function generate(out: string, type: Type) {
    const file = `// Generated by sisyphus web
import $proto from "protobufjs";
import $reflection from "./_reflection"
import {defaultValue as $defaultValue} from "@sisyphus.js/core";

${normalizeComment(type.comment)}export interface I {
    /** Any type_url */
    typeUrl?: string;

    /** Any value */
    value?: Uint8Array;`
}

function generateFields(type: Type): string {
    let result: string[] = []
    return result.join(",\n")
}